name: Deploy Hexo site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # 如果使用submodule则需要这行
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-cli -g
          npm install hexo-theme-butterfly --save  # 确保安装主题
          npm install hexo-renderer-pug hexo-renderer-stylus --save  # 安装主题依赖
          
      - name: Build
        run: |
          hexo clean
          hexo generate
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
          clean: true
